export default {
    CREATE_KEYS: [
        'createdAt',
        'cost',
        'description',
        'name',
        'producerId',
        'quantity',
        'type',
        'updatedAt',
    ],
    PRODUCER_DATA: [
        'email',
        'firstName',
        'lastName',
        'phoneNumber',
        'state',
        'address',
        'country',
        'address',
        'city',
    ],
    PRODUCT_CREATED: 'Product successfully added!',
    PRODUCT_DELETED: 'Product successfully deleted!',
    PRODUCT_UPDATED: 'Product successfully updated!',
};
