export default {
    INVALID_SIGNIN: "Invalid password, login unsuccessful",
    LOGOUT: 'Logged out successfully',
    NO_EMAIL_PASSWORD: 'Error: Email or Password cannot be blank.',
    SUCCESSFUL_SIGNIN: 'Valid sign in',
    USERINFO: [
        '_id',
        'address',
        'city',
        'country',
        'createdAt',
        'email',
        'firstName',
        'lastName',
        'phoneNumber',
        'state',
        'updatedAt',
        'username',
    ],
    USER_NOT_FOUND: 'Cannnot find any user with the email or password',
};
