module.exports = {
    ADD_PRODUCER: 'Producer successfully added!',
    ADD_PRODUCT: 'Product successfully added!',
    DELETE_PRODUCER: 'Producer successfully deleted!',
    DELETE_PRODUCT: 'Product successfully deleted!',
    INVALID_SIGNIN: "Invalid password, login unsuccessful",
    LOGOUT: 'Logged out successfully',
    NO_EMAIL_PASSWORD: 'Error: Email or Password cannot be blank.',
    SIGNED_UP: 'Signed up successfully',
    SUCCESSFUL_SIGNIN: 'Valid sign in',
    UPDATE_PRODUCER: 'Producer successfully updated!',
    UPDATE_PRODUCT: 'Product successfully updated!',
    USER_EXIST: 'Error: Account already exist.',
    USER_NOT_FOUND: 'Cannnot find any user with the email  or password',
};
