/* Form Strings*/
export const SIGNUP_STRINGS = {
    AGREEMENT: "agreement",
    CHECKED: "checked",
    CIRCLE: "circle",
    CLASSNAME_AGREEMENT: "agreement_quote",
    CLASSNAME_FORM: "signup_form",
    CLASSNAME_SCROLLBAR: "scrollbar",
    CLASSNAME_SIGNUP: "signup-form-button",
    CONFIRM: "confirm",
    EMAIL: "email",
    FIRSTNAME: "firstname",
    ICON: "question-circle-o",
    LABEL_1: "E-mail",
    LABEL_2: "First name",
    LABEL_3: "Last name",
    LABEL_4: "Location",
    LABEL_5: "Confirm Password",
    LASTNAME: "lastname",
    MESSAGE_1: "The input is not valid E-mail!",
    MESSAGE_2: "Please input your E-mail!",
    MESSAGE_3: "Please input your first name!",
    MESSAGE_4: "Please input your last name!",
    MESSAGE_5: "What do you want users to call you?",
    MESSAGE_6: "Please input your username!",
    MESSAGE_7: "Please input your location!",
    MESSAGE_8: "Please input your password!",
    MESSAGE_9: "Please confirm your password!",
    PASSWORD: "password",
    PRIMARY: "primary",
    READ: "I have read the ",
    SUBMIT: "submit",
    TITLE: "Sign up",
    TITLE_1: "title",
    USERNAME: "username",
    VERTICLE: "verticle",
};
