export const PRODUCT = {
    ACTIONS: {
        INFO_CIRCLE: 'info-circle',
        SHOPPING: 'shopping',
        SHOPPING_CART: 'shopping-cart',
    },
    CARD_IMAGE: 'card-image',
    DEFAULT_DESCRIPTION: 'This is the product description',
    MODAL_INFO: {
        BUY: 'Buy Now',
        CANCEL: 'Cancel',
        COST: 'Cost:',
        EMAIL: 'Email:',
        LOCATION: 'Location:',
        PHONE: 'Phone #:',
        PRODUCERS_NAME: `Producer's Name:`,
        QUANTITY: 'Available Quantity:',
    },
    TAG_COLOR: 'gold',
};

export const EXAMPLE_PRODUCTS = [
    {
        cost: '₦1,200',
        email: ' ',
        image: '/egg-crates.jpeg',
        location: 'Owerri Imo State',
        name: 'Egg crates',
        phone: ' ',
        quantity: '1000',
    },
    {
        cost: '₦10,000',
        email: ' ',
        image: '/PalmOil.JPG',
        location: ' Ondo state',
        name: 'Palm oil',
        phone: ' ',
        quantity: '500 gallons',
    },
    {
        cost: '₦11,500',
        email: ' ',
        image: '/onion-bags.jpg',
        location: 'Zaria, Kaduna state',
        name: 'Onion bags',
        phone: ' ',
        quantity: '100',
    },
    {
        cost: '₦1,500',
        email: ' ',
        image: '/GroundnutOil.jpeg',
        location: 'Shoprite, Owerri, Imo state',
        name: 'Vegetable Oil ',
        phone: ' ',
        quantity: '600',
    },
    {
        cost: '₦1.350',
        email: 'myemail@example.com',
        image: '/poultry-chicken.jpg',
        location: 'Niger state',
        name: "Abu's farm",
        phone: ' ',
        quantity: '1000',
    },
    {
        cost: '₦500',
        email: 'myemail@example.com',
        image: '/greenBanana.jpeg',
        location: 'Edo state',
        name: 'Green banana',
        phone: ' ',
        quantity: '400 bunches',
    },
    {
        cost: '₦15,500',
        email: 'myemail@example.com',
        image: '/bagsofrice.jpg',
        location: 'Gurara, Niger state',
        name: 'Bags of rice',
        phone: ' ',
        quantity: '87',
    },
    {
        cost: '₦4,500',
        email: 'myemail@example.com',
        image: '/Drypepper.jpg',
        location: '',
        name: 'Dry pepper',
        phone: ' ',
        quantity: '50',
    },
    {
        cost: '₦750',
        email: 'myemail@example.com',
        image: '/lettuse.jpg',
        location: '',
        name: 'Lettuses',
        phone: ' ',
        quantity: '550',
    },
    {
        cost: '₦5000',
        email: 'myemail@example.com',
        image: '/freshfarm.JPG',
        location: '',
        name: 'Fresh Farm',
        phone: ' ',
        quantity: '150',
    },
    {
        cost: '₦3,500',
        email: 'myemail@example.com',
        image: '/carrot.jpg',
        location: '',
        name: 'Carrot',
        phone: ' ',
        quantity: '3000',
    },
    {
        cost: '₦1,299',
        email: 'myemail@example.com',
        image: '/poultry.jpg',
        location: '',
        name: 'Poultry',
        phone: ' ',
        quantity: '2500',
    },
    {
        cost: '₦10,000',
        email: 'myemail@example.com',
        image: '/tomatoes.jpg',
        location: 'benue state',
        name: 'Tomatoes',
        phone: ' ',
        quantity: '500  baskets',
    },
    {
        cost: '₦15,000',
        email: 'myemail@example.com',
        image: '/beans.jpg',
        location: 'Niger state',
        name: 'Bag of beans',
        phone: ' ',
        quantity: '150 bags',
    },
    {
        cost: '₦2,000',
        email: 'myemail@example.com',
        image: '/prawn.jpg',
        location: 'Imo state',
        name: 'Prawn',
        phone: ' ',
        quantity: '30bags',
    },
    {
        cost: '₦500',
        email: 'myemail@example.com',
        image: '/Fruits.jpg',
        location: 'Ore, ondo state',
        name: "Jamal's fruit store",
        phone: ' ',
        quantity: ' ',
    },
];

export const PRODUCT_LIST_CLASSNAME = 'product-list';

export const CAROUSEL_DATA = [
    {
        src: '/carousel-placeholder-1.png',
        text: 'This is Image 1',
    },
    {
        src: '/carousel-placeholder-1.png',
        text: 'This is Image 2',
    },
    {
        src: '/carousel-placeholder-1.png',
        text: 'This is Image 3',
    },
];