export const FETCH_USER_DATA = "FETCH_USER_DATA";
// export const REQUEST_USER_DATA = "REQUEST_USER_DATA";
// export const REQUEST_USER_FAILURE = "REQUEST_USER_FAILURE";
// export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
// export const UPDATE_FAILURE = "UPDATE_FAILURE";
